name: seaice-diagnostics
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - xarray
  - matplotlib
  - cartopy
  - pillow
  - netcdf4
  - dask
  - tqdm
  - pytest
  - pip
  - pip:
      - -e .
